# Generated by Django 6.0.8 on 2026-10-02 11:24

import django.db.models.deletion
import employees.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.FileField(blank=True, default='', upload_to=employees.models.profile_photo_path),
        ),
        migrations.AddField(
            model_name='leave',
            name='document',
            field=models.FileField(blank=True, default='', upload_to=employees.models.leave_document_path),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('allocated', models.PositiveSmallIntegerField(help_text='Days allowed for this year')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='employees.employee')),
            ],
            options={
                'ordering': ['employee', 'year', 'leave_type'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('kind', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='employees_n_recipie_651f3e_idx')],
            },
        ),
    ]
